# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: moy
subtitle:
description: "The Progressive JavaScript Framework"
author: YonYou FED
email:
language:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tinper.org
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: moy
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:iuap-design/tinper-docs.git

feed:
  type: atom
  path: atom.xml
  limit: 20

alias:
  moy/clockpicker.html: moy/kero/clockpicker.html
  moy/combobox_ex.html: moy/kero/combobox_ex.html
  moy/currency_ex.html: moy/kero/currency_ex.html
  moy/ex_checkbox.html: moy/kero/ex_checkbox.html
  moy/ex_checkboxdata.html: moy/kero/ex_checkboxdata.html
  moy/ex_datetime.html: moy/kero/ex_datetime.html
  moy/ex_month.html: moy/kero/ex_month.html
  moy/ex_monthdate.html: moy/kero/ex_monthdate.html
  moy/ex_pagination.html: moy/kero/ex_pagination.html
  moy/ex_percent.html: moy/kero/ex_percent.html
  moy/ex_progress.html: moy/kero/ex_progress.html
  moy/ex_radio.html: moy/kero/ex_radio.html
  moy/ex_switch.html: moy/kero/ex_switch.html
  moy/ex_time.html: moy/kero/ex_time.html
  moy/ex_validate.html: moy/kero/ex_validate.html
  moy/ex_year.html: moy/kero/ex_year.html
  moy/ex_yearmonth.html: moy/kero/ex_yearmonth.html
  moy/grid1.html: moy/kero/grid1.html
  moy/gridValidate.html: moy/kero/gridValidate.html
  moy/mainChild.html: moy/kero/mainChild.html
  moy/module.html: moy/kero/module.html
  moy/moduleapi.html: moy/kero/moduleapi.html
  moy/textarea.html: moy/kero/textarea.html
  moy/textfield.html: moy/kero/textfield.html
  moy/tree.html: moy/kero/tree.html
